version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    versioning-strategy: "widen"
    labels:
      - "dependencies"
      - "automerge"
    assignees:
      - "peppapig450"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    allow:
      - dependency-type: "direct"
    groups:
      react-dependencies:
        patterns:
          - "react"
          - "react-dom"
          - "react*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
