name: 'Enable auto-merge for Dependabot PRs'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  enable-auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
